apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-gpu
spec:
  template:
    spec:
      containers:
      - name: pytorch-gpu
        image: inductor/pytorch-gpu
        resources:
          limits:
            nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 4
